'use strict';
const $=s=>document.querySelector(s);
const layers=[
['I THINK','腦海中的聲音','安放','先讓腦海，空出一點位置。','待辦事項、回憶、心裡的自言自語，都可能正在發聲。察覺它們，再輕輕放下；不必責怪自己分心。','留意一個浮現的念頭。不追著它走，把注意力交回身體。'],
['I AM','身體本身的聲音','呼吸','你在這裡，就已經有聲音。','聽見自然的呼吸、吞嚥，以及衣領邊微小的起伏。聲音不是從遠方開始，而是從你存在的地方開始。','維持自己的呼吸節奏。聽一口氣進來，再聽它離開。'],
['I TOUCH','我接觸而生的聲音','觸碰','世界，在接觸的地方回應。','手指、衣料、鞋底，每一次接觸都讓你參與聲景。注意：這一層是你自己的行動所製造的聲音。','輕輕摩擦指尖或袖口。留意動作停止後，聲音如何消失。'],
['I SEE','我看見聲源的聲音','看見','讓耳朵，與眼睛相遇。','把注意力延伸到眼前。看見動作發生，也聽見它留下的聲音。聲音與動作，總是同時抵達嗎？','選一個眼前正在發聲的物件。真實環境中，觀察它的動作。'],
['I KNOW','看不見，但認得的聲音','辨認','有些熟悉，不需要看見。','背後的車流、隔壁的交談、遠處的鐘聲。即使看不到，你仍可能憑經驗辨認；也容許自己的猜測出錯。','找一個看不到聲源、卻覺得熟悉的聲音。你憑什麼認出它？'],
["I DON'T KNOW",'尚未命名的聲音','未知','暫時，不必知道答案。','停留在無法辨認的聲響。先不找來源，只聽它的高低、質地、長短，以及在空間中的移動。','用擬聲詞記錄它，例如「嗡——」「窸、窸」。保留未知。']];
const scenes=[
['POST OFFICE','午後的郵局','紙張 / 印章 / 街道','排隊的午後，指尖整理信封；櫃檯落下印章，門外機車漸漸遠去。',['指尖摩擦信封','眼前櫃檯的印章','門外熟悉的機車','遠處斷續的細響']],
['TAIWAN OUTDOORS','島嶼的午後','微風 / 鳥鳴 / 車流','站在臺灣街角的樹蔭下，身旁葉片顫動，巷外車流緩緩經過。',['鞋底輕觸地面','眼前樹上的鳥鳴','街角外的車流','風裡難辨的顫音']],
['LIVE CONCERT','人海之中','節拍 / 低頻 / 餘韻','站在人群邊緣，舞台節拍穿過空間；在熱鬧裡，仍然保有自己的呼吸。',['指尖輕打拍子','舞台的電子節奏','身後人群的起伏','遠處模糊的共振']],
['CONCERT HALL','音樂廳的微光','木質 / 和弦 / 殘響','坐進安靜的音樂廳，舞台響起緩慢和弦，木質空間讓尾音停留。',['袖口拂過扶手','舞台上緩慢的和弦','身後座椅的細響','穹頂回來的泛音']],
['FOREST WALK','走進森林','腳步 / 林鳥 / 溪流','沿著林間小徑緩行，腳步碰觸落葉；鳥鳴在枝間轉移，溪流藏在視線之外。',['踩上落葉的腳步','枝間的林鳥','看不見的溪流','樹林深處不明的輕響']]];
let layer=0,scene=4,playing=false,real=false,guided=false,elapsed=0,stageTime=0,engine=null;
let notes={};try{notes=JSON.parse(localStorage.getItem('sound-spheres-notes')||'{}')}catch{};
const key=()=>`${scene}-${layer}`;
$('#steps').innerHTML=layers.map((l,i)=>`<button class="step" data-layer="${i}"><small>0${i+1}</small><strong>${l[0]}</strong><span>${l[1]}</span></button>`).join('');
$('#orb').innerHTML=layers.map((l,i)=>`<div class="ring" style="--size:${24+i*15}%"></div>`).join('');
$('#sceneCards').innerHTML=scenes.map((s,i)=>`<button class="scene" data-scene="${i}" aria-label="選擇${s[1]}"><div class="landscape"><i>SCENE / 0${i+1}</i></div><div class="scene-text"><small>${s[0]}</small><strong>${s[1]}</strong><span>${s[2]}</span></div></button>`).join('');
function render(){const l=layers[layer];document.querySelectorAll('.step').forEach((e,i)=>{e.classList.toggle('active',i===layer);e.setAttribute('aria-pressed',i===layer)});document.querySelectorAll('.ring').forEach((e,i)=>e.classList.toggle('active',i<=layer));document.querySelectorAll('.scene').forEach((e,i)=>{e.classList.toggle('selected',i===scene);e.setAttribute('aria-pressed',i===scene)});$('#orbEnglish').textContent=l[0];$('#orbWord').textContent=l[2];$('#breath').textContent=layer===0?'讓念頭慢慢沉澱':layer===1?'依照自己的節奏呼吸':'讓注意力向外延伸';$('#stepMeta').textContent=`0${layer+1} / ${l[0]}`;$('#stepTitle').textContent=l[3];$('#stepCopy').textContent=l[4];$('#stepAction').textContent=l[5]+(layer>=2&&!real?` 聲景示意：${scenes[scene][4][layer-2]}。`:'');$('#noteLabel').textContent=`${scenes[scene][1]} · ${l[0]} · ${l[1]}`;$('#notes').value=notes[key()]||'';$('#sceneDetail').textContent=scenes[scene][3];$('#play').innerHTML=playing?'暫停聆聽 <span>Ⅱ</span>':'開始聆聽 <span>↗</span>';$('#auto').textContent=guided?'Ⅱ 停止自動引導':'▷ 六分鐘引導';$('#next').textContent=layer===5?'回到內在 ↺':'下一層 →';$('#status').textContent=(playing?(real?'真實環境 · 聆聽你所在的地方':`${scenes[scene][1]} · ${guided?'六分鐘引導':'自由探索'}`):'已暫停 · 依自己的步調探索');$('#mode').textContent=real?'切換：示意聲景':'切換：聆聽真實環境';document.body.classList.toggle('playing',playing);if(engine)engine.mix();}
function setLayer(n){layer=n;stageTime=0;render()}
class SoundField{
 constructor(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC)throw Error('unsupported');this.ctx=new AC();this.master=this.ctx.createGain();this.master.gain.value=0;this.compressor=this.ctx.createDynamicsCompressor();this.master.connect(this.compressor);this.compressor.connect(this.ctx.destination);this.buses=Array.from({length:6},()=>{let g=this.ctx.createGain();g.gain.value=0;g.connect(this.master);return g});this.buff=this.ctx.createBuffer(1,this.ctx.sampleRate*4,this.ctx.sampleRate);let b=this.buff.getChannelData(0),last=0;for(let i=0;i<b.length;i++){last=(last+.04*(Math.random()*2-1))/1.04;b[i]=last*3.5}this.tick=0;this.loop=setInterval(()=>this.schedule(),650);this.bed();}
 noise(bus,freq,gain,pan,duration=1){const c=this.ctx,t=c.currentTime,s=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain(),p=c.createStereoPanner();s.buffer=this.buff;s.loop=true;f.type='bandpass';f.frequency.value=freq;f.Q.value=.65;p.pan.value=pan;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.08);g.gain.exponentialRampToValueAtTime(.0001,t+duration);s.connect(f);f.connect(g);g.connect(p);p.connect(this.buses[bus]);s.start(t,Math.random()*2);s.stop(t+duration+.1);s.onended=()=>{s.disconnect();f.disconnect();g.disconnect();p.disconnect()};}
 tone(bus,freq,gain,pan,duration=1,type='sine',end=null){const c=this.ctx,t=c.currentTime,o=c.createOscillator(),g=c.createGain(),p=c.createStereoPanner();o.type=type;o.frequency.setValueAtTime(freq,t);if(end)o.frequency.exponentialRampToValueAtTime(end,t+duration);p.pan.value=pan;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(gain,t+.035);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(p);p.connect(this.buses[bus]);o.start();o.stop(t+duration+.1);o.onended=()=>{o.disconnect();g.disconnect();p.disconnect()};}
 bed(){this.noise(1,420,.14,0,4);}
 mix(){const t=this.ctx.currentTime;this.master.gain.setTargetAtTime(playing&&!real?Number($('#volume').value)/100*.65:0,t,.35);this.buses.forEach((g,i)=>g.gain.setTargetAtTime(i===0?0:i<=layer?(i===layer?1:.45):0,t,.5));}
 schedule(){if(!playing||real||this.ctx.state!=='running')return;let n=this.tick++,pan=Math.sin(n*.7)*.75;if(n%12===0)this.bed();if(layer>=2){if(scene===4)this.noise(2,700,.32,n%2?.35:-.35,.28);else if(n%3===0)this.noise(2,scene===0?1600:900,.17,-.25,.3)}if(layer>=3){if(scene===0&&n%5===0){this.tone(3,170,.15,.3,.13,'triangle',65);this.noise(3,1800,.2,.3,.1)}if((scene===1||scene===4)&&n%4===0){this.tone(3,1800+Math.random()*700,.035,pan,.23,'sine',2900);this.tone(3,2600,.018,-pan,.4,'sine',1700)}if(scene===2){this.tone(3,90,.1,0,.22,'sine',42);if(n%2)this.noise(3,3200,.09,.2,.16);if(n%4===0)this.tone(3,[110,130.81,146.83,98][Math.floor(n/4)%4],.05,-.3,.6,'triangle')}if(scene===3&&n%6===0){const root=[130.81,146.83,110,98][Math.floor(n/6)%4];[1,1.25,1.5,2].forEach((r,i)=>{this.tone(3,root*r,.026,(i-1.5)*.35,3.8,'triangle');this.tone(3,root*r*2,.008,(1.5-i)*.4,4.5)})}}if(layer>=4&&n%4===0){this.noise(4,scene===4?2100:scene===2?520:scene===3?800:200,scene===4?.2:.16,pan,3);if(scene===0||scene===1)this.tone(4,80,.028,pan,2.8,'triangle',120)}if(layer>=5&&n%9===0){this.tone(5,340+Math.random()*300,.017,-pan,4,'sine',220+Math.random()*300);this.noise(5,1200,.07,pan,2.5)}}
}
async function start(){try{if(!real){engine??=new SoundField();await engine.ctx.resume()}playing=true;render()}catch{$('#status').textContent='瀏覽器無法啟動音訊，請切換真實環境模式。'}}
$('#play').onclick=()=>{if(playing){playing=false;render()}else start()};$('#steps').onclick=e=>{const b=e.target.closest('[data-layer]');if(b){guided=false;setLayer(+b.dataset.layer)}};$('#sceneCards').onclick=e=>{const b=e.target.closest('[data-scene]');if(b){scene=+b.dataset.scene;layer=0;stageTime=0;render()}};$('#next').onclick=()=>setLayer((layer+1)%6);$('#mode').onclick=async()=>{real=!real;if(playing&&!real)await start();render()};$('#volume').oninput=()=>engine?.mix();$('#auto').onclick=async()=>{guided=!guided;if(guided){layer=0;elapsed=0;stageTime=0;await start()}render()};$('#notes').oninput=()=>{notes[key()]=$('#notes').value;try{localStorage.setItem('sound-spheres-notes',JSON.stringify(notes));$('#saveStatus').textContent='已儲存在此瀏覽器。'}catch{$('#saveStatus').textContent='瀏覽器無法儲存，請在離開前匯出筆記。'}};$('#download').onclick=()=>{let txt='# 我的聲音球體\n\n'+new Date().toLocaleString('zh-TW')+'\n\n';for(let s=0;s<5;s++)for(let l=0;l<6;l++)if(notes[`${s}-${l}`])txt+=`## ${scenes[s][1]} / ${layers[l][0]}\n${notes[`${s}-${l}`]}\n\n`;let url=URL.createObjectURL(new Blob([txt],{type:'text/markdown;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='我的聲音球體.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};$('#about').onclick=()=>$('#info').showModal();$('#close').onclick=()=>$('#info').close();setInterval(()=>{if(!playing)return;elapsed++;stageTime++;$('#timer').textContent=`${String(Math.floor(elapsed/60)).padStart(2,'0')}:${String(elapsed%60).padStart(2,'0')}`;if(guided&&stageTime>=60){if(layer<5)setLayer(layer+1);else{playing=false;guided=false;render();$('#status').textContent='練習完成 · 留下一筆，將聆聽帶回生活。'}}},1000);document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing){playing=false;render()}});render();
