'use strict';
const THOUGHTS = [
  {
    "id": "deadline",
    "title": "待辦太多",
    "voice": "Puck",
    "text": "作業還沒交，報告也還沒寫。等一下是不是又要開會？時間怎麼又不夠了，先做哪一件啊？",
    "style": "Read only the exact Traditional Chinese transcript in natural Taiwan Mandarin. Perform a private inner monologue: quick, restless, slightly anxious, conversational muttering, close and dry. Clearly intelligible rather than breathy whispering. Do not shout, sing, add words, or include music or sound effects. Use varied pacing with small hesitations, like everyday worries circling in the mind.",
    "model": "gemini-3.1-flash-tts-preview",
    "file": "audio/think-deadline.mp3",
    "type": "AI-generated speech",
    "generated_on": "2026-09-07",
    "duration_seconds": 7.63,
    "lufs": -21.75,
    "true_peak_dbtp": -3.44,
    "processing": "100 Hz high-pass, 10 kHz low-pass, loudness normalization target -20 LUFS / -3 dBTP, 0.55-second end padding, 25 ms fade-in, mono 44.1 kHz / 160 kbps MP3"
  },
  {
    "id": "social",
    "title": "別人怎麼想",
    "voice": "Kore",
    "text": "剛剛那句話是不是說錯了？他怎麼還沒回訊息？是不是在生我的氣？早知道就不要那樣講了。",
    "style": "Read only the exact Traditional Chinese transcript in natural Taiwan Mandarin. Perform a private inner monologue: quick, restless, slightly anxious, conversational muttering, close and dry. Clearly intelligible rather than breathy whispering. Do not shout, sing, add words, or include music or sound effects. Use varied pacing with small hesitations, like everyday worries circling in the mind.",
    "model": "gemini-3.1-flash-tts-preview",
    "file": "audio/think-social.mp3",
    "type": "AI-generated speech",
    "generated_on": "2026-09-07",
    "duration_seconds": 9.47,
    "lufs": -20.16,
    "true_peak_dbtp": -5.3,
    "processing": "100 Hz high-pass, 10 kHz low-pass, loudness normalization target -20 LUFS / -3 dBTP, 0.55-second end padding, 25 ms fade-in, mono 44.1 kHz / 160 kbps MP3"
  },
  {
    "id": "perfect",
    "title": "還不夠好",
    "voice": "Fenrir",
    "text": "別人都已經做完了，我怎麼還卡在這裡？如果做得不好怎麼辦？再改一下，再改一下，還是不夠好。",
    "style": "Read only the exact Traditional Chinese transcript in natural Taiwan Mandarin. Perform a private inner monologue: quick, restless, slightly anxious, conversational muttering, close and dry. Clearly intelligible rather than breathy whispering. Do not shout, sing, add words, or include music or sound effects. Use varied pacing with small hesitations, like everyday worries circling in the mind.",
    "model": "gemini-3.1-flash-tts-preview",
    "file": "audio/think-perfect.mp3",
    "type": "AI-generated speech",
    "generated_on": "2026-09-07",
    "duration_seconds": 10.87,
    "lufs": -21.9,
    "true_peak_dbtp": -3.45,
    "processing": "100 Hz high-pass, 10 kHz low-pass, loudness normalization target -20 LUFS / -3 dBTP, 0.55-second end padding, 25 ms fade-in, mono 44.1 kHz / 160 kbps MP3"
  },
  {
    "id": "daily",
    "title": "日常小混亂",
    "voice": "Laomedeia",
    "text": "鑰匙放哪裡？手機是不是快沒電了？等一下要買什麼？晚餐吃什麼？欸，我剛剛到底要做什麼？",
    "style": "Read only the exact Traditional Chinese transcript in natural Taiwan Mandarin. Perform a private inner monologue: quick, restless, slightly anxious, conversational muttering, close and dry. Clearly intelligible rather than breathy whispering. Do not shout, sing, add words, or include music or sound effects. Use varied pacing with small hesitations, like everyday worries circling in the mind.",
    "model": "gemini-2.5-flash-preview-tts",
    "file": "audio/think-daily.mp3",
    "type": "AI-generated speech",
    "generated_on": "2026-09-07",
    "duration_seconds": 8.282,
    "lufs": -21.0,
    "true_peak_dbtp": -3.39,
    "processing": "100 Hz high-pass, 10 kHz low-pass, loudness normalization target -20 LUFS / -3 dBTP, 0.55-second end padding, 25 ms fade-in, mono 44.1 kHz / 160 kbps MP3"
  },
  {
    "id": "future",
    "title": "明天怎麼辦",
    "voice": "Achird",
    "text": "明天會順利嗎？萬一出錯怎麼辦？下個月的計畫呢？要不要先想一個備案？還是再想一個？",
    "style": "Read only the exact Traditional Chinese transcript in natural Taiwan Mandarin. Perform a private inner monologue: quick, restless, slightly anxious, conversational muttering, close and dry. Clearly intelligible rather than breathy whispering. Do not shout, sing, add words, or include music or sound effects. Use varied pacing with small hesitations, like everyday worries circling in the mind.",
    "model": "gemini-2.5-flash-preview-tts",
    "file": "audio/think-future.mp3",
    "type": "AI-generated speech",
    "generated_on": "2026-09-07",
    "duration_seconds": 7.881,
    "lufs": -19.82,
    "true_peak_dbtp": -3.39,
    "processing": "100 Hz high-pass, 10 kHz low-pass, loudness normalization target -20 LUFS / -3 dBTP, 0.55-second end padding, 25 ms fade-in, mono 44.1 kHz / 160 kbps MP3"
  }
];
